apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: y0wg9y6ru-python 
  janus-idp.io/tekton: y0wg9y6ru-python
  backstage.io/kubernetes-id: y0wg9y6ru-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: y0wg9y6ru-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml