apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: y0wg9y6ru-python
  janus-idp.io/tekton: y0wg9y6ru-python
  backstage.io/kubernetes-id: y0wg9y6ru-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: y0wg9y6ru-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
