apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: y0wg9y6ru-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: y0wg9y6ru-python 
  name: y0wg9y6ru-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: y0wg9y6ru-python 
